### ISSUE TITLE
Unable to pass parameters to `setupBubble()`/`setupNotificationBuilder()` from `onStartCommand()`

### ISSUE THREAD

**Issue by moazelsawaf** [TorryDo/Floating-Bubble-View#28] opened 2023-04-11 21:37 UTC
Hello Dear,

I was using version `0.5.0` and everything was working fine, but I wanted to upgrade to the latest version (`v0.5.1`) to have the new updates, unfortunlly, my class which implements the `FloatingBubbleService()` has an override for `onStartCommand()` method, once I upgraded the dependency, this overridden method stopped working, it is not called at all.

**NOTE:** I have made sure that I am registering the service in the `<application>` tag in the `Manifest` file and starting the service with an intent.

Also I would like to mention that I am using this method to initialize a `lateinit` variable that holds a value passed from the intent that starts the service to be used inside `setupBubble()` method, so if you have a better way to do that please suggest.

I would be glad if you could help me with this issue 🙏🏻

Thanks in Advance 🙏🏻❤

**Comment by TorryDo** [comment] 2023-04-12 02:43
Hi @moazelsawaf, 

In `v0.5.1`, I removed `showBubbles()` from `onStartCommand()` (which I should have done a long time ago) and moved it to the `onCreate()` method. You can easily choose the initial view by overriding [`initialRoute()`](https://github.com/TorryDo/Floating-Bubble-View/blob/master/README.md#usage)

The reason for this is that if you pass the intent to the service multiple times throughout the service lifecycle, you must override the `onStartCommand()` method first. Otherwise, the bubble will appear overlapped each time you send the intent. 

Therefore, in this version, onStartCommand() is not being touched, and it should behave normally. The reason why the overridden method is not working may be something else. 

If you are still experiencing the issue, please provide more information so that we can solve it step by step?

Thank you!

**Comment by TorryDo** [comment] 2023-04-12 14:30
Looks like a bug!. 

After a short investigation, I found out that it's hard to pass bubble properties via `onStartCommand()` to  `setupBubble()`. This is a silly bug that can be fixed in a blink of an eye. I'll fix it in the next version.

Thank you for pointing it out 💖.

**Comment by moazelsawaf** [comment] 2023-04-12 15:06
Great ❤

Thank you so much @TorryDo for caring 🙏🏻❤

Waiting for the next release Insha'Allah 💪🏻❤

**Comment by TorryDo** [comment] 2023-04-16 10:59
The issue is now gone in [`v0.5.2`](https://github.com/TorryDo/Floating-Bubble-View/releases/tag/0.5.2)

If you have any further concerns, don't hesitate to reopen the issue.

Cheers 🍺🍻

**Comment by moazelsawaf** [comment] 2023-04-17 02:46
Unfortunately, the issue still exists, `setupBubble()` is being called before `onStartCommand()` so I am still unable to initialize the variables.

📃 Here are the logs of printing a statement in the first line of each method:

```
2023-04-17 04:41:49.114 12555-12555 BubbleService           dev.moaz.dash_bubble_example         D  setupBubble
2023-04-17 04:41:49.135 12555-12555 BubbleService           dev.moaz.dash_bubble_example         D  onStartCommand
```

**Comment by TorryDo** [comment] 2023-04-17 02:55
That's weird🤔. Did you override `initialRoute()` and return `Route.Empty`?

**Comment by moazelsawaf** [comment] 2023-04-17 03:05
No, I am not overriding `initialRoute()` ...

I tried now and overridden it to return `Route.Empty`, but `setupBubble()` method stopped being called at all ... 😔

📃 Here are the new logs:

```
2023-04-17 05:04:33.646 18188-18188 BubbleService           dev.moaz.dash_bubble_example         D  initialRoute
2023-04-17 05:04:33.648 18188-18188 BubbleService           dev.moaz.dash_bubble_example         D  setupNotificationBuilder
2023-04-17 05:04:33.652 18188-18188 BubbleService           dev.moaz.dash_bubble_example         D  onStartCommand
```

**Comment by TorryDo** [comment] 2023-04-17 03:11
I'm confused now 😅. Please take a quick look at [Sample](https://github.com/TorryDo/Floating-Bubble-View/blob/master/app/src/main/java/com/torrydo/testfloatingbubble/MyServiceKt.kt) (line 41 -> 60)

Is your code somthing similar to this?

```kotlin

    override fun initialRoute(): Route {
        return Route.Empty
    }

    private var size = 0

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {

        val _size = intent?.getIntExtra("size", 0)

        size = _size ?: 0

        showBubbles()

        return START_STICKY
    }
```

**Comment by moazelsawaf** [comment] 2023-04-17 03:18
Hmm, sorry I was not calling `showBubbles()` method, now after calling it the issue should be solved for `setupBubble()` because I have the control to decide when to call it, but the problem persists for `setupNotificationBuilder()` because it is still being called before `onStartCommand()` method.

📃 Here are the new logs:

```
2023-04-17 05:15:29.895 21779-21779 BubbleService           dev.moaz.dash_bubble_example         D  initialRoute
2023-04-17 05:15:29.897 21779-21779 BubbleService           dev.moaz.dash_bubble_example         D  setupNotificationBuilder
2023-04-17 05:15:29.900 21779-21779 BubbleService           dev.moaz.dash_bubble_example         D  onStartCommand
2023-04-17 05:15:29.900 21779-21779 BubbleService           dev.moaz.dash_bubble_example         D  setupBubble
```

**Comment by TorryDo** [comment] 2023-04-17 03:24
So you want to pass parameters to notification too?

You can do that by using this code, which will update the notification. the `setupNotificationBuilder()` is basically just the method to init the notification.

```kotlin
        val notification = // your notification
        NotificationManagerCompat.from(this).notify(notificationId(), notification)
```

**Comment by moazelsawaf** [comment] 2023-04-17 03:32
Do you mean I should not override `setupNotificationBuilder()` method for now and use your idea of updating the notification in `onStartCommand()` after initializing my variables?

**Comment by TorryDo** [comment] 2023-04-17 03:37
Nope, you can simply using the code above in `onStartCommand()`. It'll update the current notification.

**Comment by moazelsawaf** [comment] 2023-04-17 03:45
That is what I meant 👌🏻

It worked, but unfortunately, I have to request a new unnecessary permission from the user which is `POST_NOTIFICATIONS`, that would complicate the process.

**Comment by TorryDo** [comment] 2023-04-17 04:22
Maybe I have to revamp `setupNotificationBuilder()` soon. 

Thank you!

**Comment by TorryDo** [comment] 2023-04-29 10:30
hi @moazelsawaf , 👋
You can pass parameters to the notification now. Simply by following these steps:

- update version to `v0.5.3`
- override "initialNotification" and return null
- pass the notification to `notify(Notification)`.

In Android 13+, the notifications are only visible if "POST_NOTIFICATIONS" permission is granted. However, the service will still run fine without the notification.

Thank you!

**Closed by TorryDo** 2023-04-29 10:30 UTC
Labels: bug

**Comment by moazelsawaf** [comment] 2023-04-29 17:00
Thanks for your concerns ❤

Should I handle the notification my self or it is already handled inside the library?

**Comment by TorryDo** [comment] 2023-04-30 00:48
If you want the notification visible, fist include "POST_NOTIFICATIONS" in your manifest file. Then ask for permission. 
If permission is not granted, the notification won't visible, 'initialNotification' and 'notify' will still able to call but without notification.

**Comment by moazelsawaf** [comment] 2023-04-30 19:01
Thank you so much ❤

Now everything is clear, I will add the permission request for Android 13, but I wanted to ask a question, in the old logic in the earlier versions, would it be also a must to request the `POST_NOTIFICATIONS` permission in Android 13?

**Comment by TorryDo** [comment] 2023-05-01 02:29
No, it's not required.
Foreground notification working fine in ealier versions.

You can find more info here: [Android Service](https://developer.android.com/guide/components/foreground-services).
Thank you.

**Comment by moazelsawaf** [comment] 2023-05-01 03:39
Thank you so much for the clarification 🙏🏻❤️
